# Generated by Django 5.2 on 2025-12-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_trashitem_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trashitem',
            name='seller',
        ),
    ]
