# Generated by Django 6.0 on 2025-12-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_trashitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashitem',
            name='category',
            field=models.CharField(choices=[('plastics', 'Plastics'), ('metals', 'Metals'), ('paper', 'Paper'), ('glass', 'Glass'), ('electronics', 'Electronics'), ('textiles', 'Textiles'), ('organic', 'Organic'), ('others', 'Others')], default='', max_length=100),
        ),
    ]
