# Generated by Django 6.0 on 2025-12-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_order_checkout_request_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashitem',
            name='approval_status',
            field=models.BooleanField(default=False),
        ),
    ]
