# Generated by Django 5.2 on 2025-12-04 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_driverrating_comment_driverrating_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('artisan', 'Artisan'), ('buyer', 'Buyer'), ('waste_seller', 'Waste Seller')], max_length=15),
        ),
        migrations.CreateModel(
            name='WasteSellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(choices=[('factory', 'Factory'), ('household', 'Household'), ('business', 'Business'), ('institution', 'Institution'), ('other', 'Other')], default='business', max_length=50)),
                ('waste_types', models.CharField(blank=True, max_length=255)),
                ('collection_schedule', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='waste_seller_profiles/')),
                ('rating', models.FloatField(default=0.0)),
                ('total_waste_sold', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collection_count', models.PositiveIntegerField(default=0)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
