# Generated by Django 5.2 on 2025-12-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_role_wastesellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('artisan', 'Artisan'), ('buyer', 'Buyer')], max_length=10),
        ),
        migrations.DeleteModel(
            name='WasteSellerProfile',
        ),
    ]
